In [81]:
### Projeto Final Coder ###

'''
Tratamento das Bases

Descrição
* Realizar o tratamento das bases coletadas via API do projeto final na aula 12.

Aspectos a incluir
* Ajuste os nomes das colunas e linhas. 
* Filtros de linhas e colunas, se necessário
* Unstack e/ou stack.
* Tratamento do tipo das variáveis.
* Ajuste de missing.
* Tratamento de colunas string. 

Observações
* Você pode criar novas tabelas, salvando as bases brutas e as bases tratadas.
* As bases finais precisam estar totalmente ajustadas (da melhor forma possível) e salvas no banco de dados.
'''

'\nTratamento das Bases\n\nDescrição\n* Realizar o tratamento das bases coletadas via API do projeto final na aula 12.\n\nAspectos a incluir\n* Ajuste os nomes das colunas e linhas. \n* Filtros de linhas e colunas, se necessário\n* Unstack e/ou stack.\n* Tratamento do tipo das variáveis.\n* Ajuste de missing.\n* Tratamento de colunas string. \n\nObservações\n* Você pode criar novas tabelas, salvando as bases brutas e as bases tratadas.\n* As bases finais precisam estar totalmente ajustadas (da melhor forma possível) e salvas no banco de dados.\n'

In [82]:
import requests
import pandas as pd
from plyer import notification

In [83]:
def result_req(url):
    '''
    Mostra um alerta por 10 segundos na tela, informando o status da URL
    '''

    req = requests.get(url)
    reqsts = req.status_code
    reqrea = req.reason

    if reqsts == 200:
        msg = 'A conexão foi estabelecida com sucesso!'
    else:
        msg = "Falha na conexão!"
    
    notification.notify(
    title=f'STATUS DA CONEXÃO',
    message=f'{msg} Cod: {reqsts}. Info: {reqrea}',
    app_name=" ",
    timeout=10)

In [84]:
url_feriados24 = 'https://brasilapi.com.br/api/feriados/v1/2024' # lista dos feriados nacionais em 2024.
url_pix = 'https://brasilapi.com.br/api/pix/v1/participants' # lista de instituções bancárias que utilizam o pix no país.
url_corretoras = 'https://brasilapi.com.br/api/cvm/corretoras/v1' # corretoras de valores do país.

url_error = 'https://brasilapi.com.br/api/feriados/v1/20xx' # uma url com erro para validação da 'def'

In [85]:
result_req(url_feriados24)
df_feriados24 = pd.DataFrame(requests.get(url_feriados24).json())

In [86]:
result_req(url_pix)
df_pix = pd.DataFrame(requests.get(url_pix).json())

In [87]:
result_req(url_corretoras)
df_corretoras = pd.DataFrame(requests.get(url_corretoras).json())

In [88]:
df_feriados24

          date                      name      type
0   2024-01-01  Confraternização mundial  national
1   2024-02-13                  Carnaval  national
2   2024-03-29         Sexta-feira Santa  national
3   2024-03-31                    Páscoa  national
4   2024-04-21                Tiradentes  national
5   2024-05-01           Dia do trabalho  national
6   2024-05-30            Corpus Christi  national
7   2024-09-07   Independência do Brasil  national
8   2024-10-12   Nossa Senhora Aparecida  national
9   2024-11-02                   Finados  national
10  2024-11-15  Proclamação da República  national
11  2024-12-25                     Natal  national

In [89]:
df_feriados24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    12 non-null     object
 1   name    12 non-null     object
 2   type    12 non-null     object
dtypes: object(3)
memory usage: 420.0+ bytes

In [90]:
df_pix = df_pix.replace(['NA', 'N/A', 'None', ''], pd.NA)
df_pix

,ispb,nome,nome_reduzido,modalidade_participacao,tipo_participacao,inicio_operacao
0,00000000,BANCO DO BRASIL S.A.,BCO DO BRASIL S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
1,00000208,BRB - BANCO DE BRASILIA S.A.,BRB - BCO DE BRASILIA S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
2,00068987,COOPERATIVA DE CRÉDITO ARACREDI LTDA. - SICOOB...,CC ARACREDI LTDA.,PDCT,IDRT,2020-11-03T09:30:00.000Z
3,00075847,COOPERATIVA DE CRÉDITO UNICRED CENTRO-SUL LTDA...,CC UNICRED CENTRO-SUL LTDA - UNICRED CENTRO-SUL,PDCT,IDRT,2020-11-03T09:30:00.000Z
4,00106180,CENTRAL DAS COOPERATIVAS DE CRÉDITO DOS ESTADO...,"CCC DOS EST DE MT, MS E MUN DE CACOAL/RO",PDCT,IDRT,2020-11-03T09:30:00.000Z
...,...,...,...,...,...,...
798,95213211,"COOPERATIVA DE CRéDITO, POUPANçA E INVESTIMENT...",COOP SICREDI CAMINHO DAS ÁGUAS RS,PDCT,IDRT,2020-11-03T09:30:00.000Z
799,95424891,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI VALE DO RIO PARDO,PDCT,IDRT,2020-11-03T09:30:00.000Z
800,95594941,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI REG CENTRO RS/MG,PDCT,IDRT,2020-11-03T09:30:00.000Z
801,97259253,COOPERATIVA E ECONOMIA E CRÉDITO MÚTUO DOS MÉD...,CECM MÉDICOS PLANALTO MÉDIO RS - CREDISIS/CRED...,PDCT,IDRT,2021-10-04T12:53:10.567Z
802,97489280,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI INTEGRAÇÃO BAHIA,PDCT,IDRT,2020-11-03T09:30:00.000Z

In [91]:
df_pix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 803 entries, 0 to 802
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ispb                     803 non-null    object
 1   nome                     803 non-null    object
 2   nome_reduzido            803 non-null    object
 3   modalidade_participacao  803 non-null    object
 4   tipo_participacao        803 non-null    object
 5   inicio_operacao          803 non-null    object
dtypes: object(6)
memory usage: 37.8+ KB

In [92]:
df_corretoras = df_corretoras.replace(['NA', 'N/A', 'None', ''], pd.NA)
df_corretoras

,cnpj,type,nome_social,nome_comercial,status,email,telefone,cep,pais,uf,municipio,bairro,complemento,logradouro,data_patrimonio_liquido,valor_patrimonio_liquido,codigo_cvm,data_inicio_situacao,data_registro
0,76621457000185,CORRETORAS,4UM DTVM S.A.,4UM INVESTIMENTOS,CANCELADA,controle@4um.com.br,33519966,80420210,BRASIL,PR,CURITIBA,CENTRO,4º ANDAR,R. VISCONDE DO RIO BRANCO 1488,2005-12-31,4228660.18,2275,2006-10-05,1968-01-15
1,33817677000176,CORRETORAS,ABC BRASIL DISTRIBUIDORA DE TÍTULOS E VALORES ...,ABC BRASIL CORRETORA,CANCELADA,complianceregulatorio@abcbrasil.com.br,31702172,1453000,EGITO,SP,SÃO PAULO,ITAIM BIBI,2º ANDAR,"AV. CIDADE JARDIM, 803",2002-12-31,0.00,3514,2002-10-14,2002-10-14
2,10664027000132,CORRETORAS,ABERTURA CCVM LTDA,ABERTURA CCVM LTDA,CANCELADA,<NA>,<NA>,50010240,BRASIL,PE,RECIFE,<NA>,<NA>,R DO IMP.D.PEDRO II 239/CJ.102,1989-12-31,5995252.29,329,1990-06-12,1986-07-08
3,44527444000155,CORRETORAS,ABN AMRO CORRETORA DE T-TULOS E VALORES MOBILI...,<NA>,EM FUNCIONAMENTO NORMAL,canal.comunicacao@br.abnamro.com,30737417,4551010,<NA>,SP,SÃO PAULO,VILA OLIMPIA,"11¦ ANDAR, CJ. 111","RUA FIDÛNCIO RAMOS, N¦ 302, TORRE B",2022-12-31,3729687.41,3794,2022-06-20,2022-06-20
4,33819590000138,CORRETORAS,AÇÃO S.A. CORRETORA DE VALORES E CÂMBIO,ACAO SA CVC,CANCELADA,<NA>,5095755,20040040,BRASIL,RJ,RIO DE JANEIRO,CENTRO,<NA>,"PRAÇA OLAVO BILAC, 28/ SL. 608",2000-12-31,291862.38,1112,2001-04-11,1968-04-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,01170892000131,CORRETORAS,VOTORANTIM CTVM LTDA,VOTORANTIM,CANCELADA,demandasregulatorias@bancovotorantim.com.br,51711894,4794000,BRASIL,SP,SÃO PAULO,VL.GERTRUDES,TORRE A-14º ANDAR,"AV DAS NAÇÕES UNIDAS, 14.171",2017-12-31,266791832.77,3166,2018-08-27,1996-03-15
370,61769790000169,CORRETORAS,WALPIRES S/A CCTVM,WALPIRES S/A CCTVM,CANCELADA,andre@walpires.com.br,28087065,1452002,BRASIL,SP,SÃO PAULO,JARDIM PAULISTANO,1309 - 9ºANDAR,AVENIDA BRIGADEIRO FARIA LIMA,2017-12-31,7464373.90,1902,2019-09-24,1967-09-20
371,92875780000131,CORRETORAS,WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMB...,WARREN CORRETORA,EM FUNCIONAMENTO NORMAL,juridico@warren.com.br,32372273,90035191,EGITO,RS,PORTO ALEGRE,BOM FIM,2º ANDAR,"AVENIDA OSVALDO ARANHA, 720",2022-12-31,23398120.52,2534,1967-12-06,1967-12-06
372,24543688000114,CORRETORAS,WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMB...,PERFIL,CANCELADA,<NA>,2249022,52061540,BRASIL,PE,RECIFE,CASA FORTE,<NA>,"AV.17 DE AGOSTO,2579",1996-12-31,608260.02,2658,1997-02-21,1989-11-14
373,02332886000104,CORRETORAS,XP INVESTIMENTOS CCTVM S.A.,XP INVESTIMENTOS,EM FUNCIONAMENTO NORMAL,fabricio.almeida@xpi.com.br,30272237,22440032,<NA>,RJ,RIO DE JANEIRO,LEBLON,5º ANDAR,AVENIDA ATAULFO DE PAIVA 153,2022-12-31,8288904369.58,3247,1998-02-10,1997-12-05

In [93]:
df_corretoras.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   cnpj                      374 non-null    object
 1   type                      374 non-null    object
 2   nome_social               374 non-null    object
 3   nome_comercial            333 non-null    object
 4   status                    374 non-null    object
 5   email                     214 non-null    object
 6   telefone                  333 non-null    object
 7   cep                       373 non-null    object
 8   pais                      308 non-null    object
 9   uf                        373 non-null    object
 10  municipio                 373 non-null    object
 11  bairro                    271 non-null    object
 12  complemento               190 non-null    object
 13  logradouro                373 non-null    object
 14  data_patrimonio_liquido   371 non-null    object
 15  valor_patrimonio_liquido  371 non-null    object
 16  codigo_cvm                374 non-null    object
 17  data_inicio_situacao      374 non-null    object
 18  data_registro             374 non-null    object
dtypes: object(19)
memory usage: 55.6+ KB

In [94]:
df_feriados24_n = df_feriados24.rename(columns={'date': 'Data', 'name': 'Feriado Nacional'})
df_feriados24_n = df_feriados24_n.drop(columns=['type'])
df_feriados24_n['Data'] = pd.to_datetime(df_feriados24_n['Data'])
df_feriados24_n = df_feriados24_n.set_index('Feriado Nacional')
df_feriados24_n

                               Data
Feriado Nacional
Confraternização mundial 2024-01-01
Carnaval                 2024-02-13
Sexta-feira Santa        2024-03-29
Páscoa                   2024-03-31
Tiradentes               2024-04-21
Dia do trabalho          2024-05-01
Corpus Christi           2024-05-30
Independência do Brasil  2024-09-07
Nossa Senhora Aparecida  2024-10-12
Finados                  2024-11-02
Proclamação da República 2024-11-15
Natal                    2024-12-25

In [95]:
df_feriados24_n.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, Confraternização mundial to Natal
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Data    12 non-null     datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 192.0+ bytes

In [96]:
df_pix_n = df_pix.rename(columns={'nome': 'Razão Social', 'nome_reduzido': 'Nome', 'inicio_operação': 'Data de Inicio', 'ispb': 'ISPB',
                                  'modalidade_participacao': 'Modalidade', 'tipo_participacao': 'Tipo', 'inicio_operacao': 'Inicio da Operação'})
df_pix_n['Inicio da Operação'] = df_pix_n['Inicio da Operação'].str.slice(start=0, stop=10)
df_pix_n['Inicio da Operação'] = pd.to_datetime(df_pix_n['Inicio da Operação'])
df_pix_n = df_pix_n.set_index('ISPB')
df_pix_n

,Razão Social,Nome,Modalidade,Tipo,Inicio da Operação
ISPB,,,,,
00000000,BANCO DO BRASIL S.A.,BCO DO BRASIL S.A.,PDCT,DRCT,2020-11-03
00000208,BRB - BANCO DE BRASILIA S.A.,BRB - BCO DE BRASILIA S.A.,PDCT,DRCT,2020-11-03
00068987,COOPERATIVA DE CRÉDITO ARACREDI LTDA. - SICOOB...,CC ARACREDI LTDA.,PDCT,IDRT,2020-11-03
00075847,COOPERATIVA DE CRÉDITO UNICRED CENTRO-SUL LTDA...,CC UNICRED CENTRO-SUL LTDA - UNICRED CENTRO-SUL,PDCT,IDRT,2020-11-03
00106180,CENTRAL DAS COOPERATIVAS DE CRÉDITO DOS ESTADO...,"CCC DOS EST DE MT, MS E MUN DE CACOAL/RO",PDCT,IDRT,2020-11-03
...,...,...,...,...,...
95213211,"COOPERATIVA DE CRéDITO, POUPANçA E INVESTIMENT...",COOP SICREDI CAMINHO DAS ÁGUAS RS,PDCT,IDRT,2020-11-03
95424891,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI VALE DO RIO PARDO,PDCT,IDRT,2020-11-03
95594941,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI REG CENTRO RS/MG,PDCT,IDRT,2020-11-03
97259253,COOPERATIVA E ECONOMIA E CRÉDITO MÚTUO DOS MÉD...,CECM MÉDICOS PLANALTO MÉDIO RS - CREDISIS/CRED...,PDCT,IDRT,2021-10-04
97489280,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI INTEGRAÇÃO BAHIA,PDCT,IDRT,2020-11-03

In [97]:
df_pix_n.info()

<class 'pandas.core.frame.DataFrame'>
Index: 803 entries, 00000000 to 97489280
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Razão Social        803 non-null    object
 1   Nome                803 non-null    object
 2   Modalidade          803 non-null    object
 3   Tipo                803 non-null    object
 4   Inicio da Operação  803 non-null    datetime64[ns]
dtypes: datetime64[ns](1), object(4)
memory usage: 37.6+ KB

In [98]:
df_corretoras_n = df_corretoras.rename(columns={'nome_social': 'Razão Social', 'nome_comercial': 'Nome Comercial', 'cnpj': 'CNPJ',
                                  'status': 'Status', 'email': 'E-Mail', 'telefone': 'Telefone', 'cep': 'CEP', 'pais': 'País', 'uf': 'UF',
                                  'municipio': 'Município', 'bairro': 'Bairro', 'logradouro': 'Endereço', 'complemento': 'Complemento',
                                  'valor_patrimonio_liquido': 'Valor PL', 'codigo_cvm': 'Cod. CVM', 'data_registro': 'Data Registro',
                                  'data_inicio_situacao': 'Data Mudança Status'})
df_corretoras_n = df_corretoras_n.drop(columns=['type', 'data_patrimonio_liquido'])
df_corretoras_n['Data Registro'] = pd.to_datetime(df_corretoras_n['Data Registro'])
df_corretoras_n['Data Mudança Status'] = pd.to_datetime(df_corretoras_n['Data Mudança Status'])
df_corretoras_n = df_corretoras_n.set_index('Cod. CVM')
ordem_das_colunas = ['CNPJ','Razão Social','Nome Comercial','Data Registro','Valor PL','Telefone','E-Mail','Endereço',
                     'Complemento','Bairro','Município','UF','País','CEP','Status','Data Mudança Status']
df_corretoras_n = df_corretoras_n[ordem_das_colunas]
df_corretoras_n[['Telefone', 'E-Mail','Nome Comercial']] = df_corretoras_n[['Telefone', 'E-Mail','Nome Comercial']].fillna('Não informado')
df_corretoras_n[['Endereço', 'Bairro', 'Município', 'UF', 'País', 'CEP', 'Complemento']] = df_corretoras_n[['Endereço', 'Bairro', 'Município', 'UF', 'País', 'CEP', 'Complemento']].fillna('-')
df_corretoras_n[['Valor PL']] = df_corretoras_n[['Valor PL']].fillna('0.00')
df_corretoras_n['Valor PL'] = pd.to_numeric(df_corretoras_n['Valor PL'])
df_corretoras_n.head()

,CNPJ,Razão Social,Nome Comercial,Data Registro,Valor PL,Telefone,E-Mail,Endereço,Complemento,Bairro,Município,UF,País,CEP,Status,Data Mudança Status
Cod. CVM,,,,,,,,,,,,,,,,
2275,76621457000185,4UM DTVM S.A.,4UM INVESTIMENTOS,1968-01-15,4228660.18,33519966,controle@4um.com.br,R. VISCONDE DO RIO BRANCO 1488,4º ANDAR,CENTRO,CURITIBA,PR,BRASIL,80420210,CANCELADA,2006-10-05
3514,33817677000176,ABC BRASIL DISTRIBUIDORA DE TÍTULOS E VALORES ...,ABC BRASIL CORRETORA,2002-10-14,0.00,31702172,complianceregulatorio@abcbrasil.com.br,"AV. CIDADE JARDIM, 803",2º ANDAR,ITAIM BIBI,SÃO PAULO,SP,EGITO,1453000,CANCELADA,2002-10-14
329,10664027000132,ABERTURA CCVM LTDA,ABERTURA CCVM LTDA,1986-07-08,5995252.29,Não informado,Não informado,R DO IMP.D.PEDRO II 239/CJ.102,-,-,RECIFE,PE,BRASIL,50010240,CANCELADA,1990-06-12
3794,44527444000155,ABN AMRO CORRETORA DE T-TULOS E VALORES MOBILI...,Não informado,2022-06-20,3729687.41,30737417,canal.comunicacao@br.abnamro.com,"RUA FIDÛNCIO RAMOS, N¦ 302, TORRE B","11¦ ANDAR, CJ. 111",VILA OLIMPIA,SÃO PAULO,SP,-,4551010,EM FUNCIONAMENTO NORMAL,2022-06-20
1112,33819590000138,AÇÃO S.A. CORRETORA DE VALORES E CÂMBIO,ACAO SA CVC,1968-04-19,291862.38,5095755,Não informado,"PRAÇA OLAVO BILAC, 28/ SL. 608",-,CENTRO,RIO DE JANEIRO,RJ,BRASIL,20040040,CANCELADA,2001-04-11

In [99]:
df_corretoras_n.info()

<class 'pandas.core.frame.DataFrame'>
Index: 374 entries, 2275 to 3247
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CNPJ                 374 non-null    object
 1   Razão Social         374 non-null    object
 2   Nome Comercial       374 non-null    object
 3   Data Registro        374 non-null    datetime64[ns]
 4   Valor PL             374 non-null    float64
 5   Telefone             374 non-null    object
 6   E-Mail               374 non-null    object
 7   Endereço             374 non-null    object
 8   Complemento          374 non-null    object
 9   Bairro               374 non-null    object
 10  Município            374 non-null    object
 11  UF                   374 non-null    object
 12  País                 374 non-null    object
 13  CEP                  374 non-null    object
 14  Status               374 non-null    object
 15  Data Mudança Status  374 non-null    datetime64[ns]
dtypes: datetime64[ns](2), float64(1), object(13)
memory usage: 49.7+ KB