In [1]:
### Projeto Final Coder ###

'''
Primeira entrega

Para essa entrega focaremos somente nas etapas de:

✓ Escolher uma API da lista disponível;
✓ Fazer a extração de pelo menos 3 tabelas;
✓ Criar um alerta de erro usando a função alerta() do desafio da aula Fundamentos de programação III.

Formato
✓ O entregável é um link do GitHub para um arquivo .py ou .ipynb com a resolução proposta.
✓ Utilize o mesmo repositório criado na aula de GIT.   

Observações
✓ Não é necessário fazer tratamentos das tabelas, salvar no banco de dados ou documentação nesta etapa do projeto
'''

'\nPrimeira entrega\n\nPara essa entrega focaremos somente nas etapas de:\n\n✓ Escolher uma API da lista disponível;\n✓ Fazer a extração de pelo menos 3 tabelas;\n✓ Criar um alerta de erro usando a função alerta() do desafio da aula Fundamentos de programação III.\n\nFormato\n✓ O entregável é um link do GitHub para um arquivo .py ou .ipynb com a resolução proposta.\n✓ Utilize o mesmo repositório criado na aula de GIT.   \n\nObservações\n✓ Não é necessário fazer tratamentos das tabelas, salvar no banco de dados ou documentação nesta etapa do projeto\n'

In [2]:
import requests
import pandas as pd
from plyer import notification

In [3]:
def result_req(url):
    '''
    Mostra um alerta por 10 segundos na tela, informando o status da URL
    '''

    req = requests.get(url)
    reqsts = req.status_code
    reqrea = req.reason

    if reqsts == 200:
        msg = 'A conexão foi estabelecida com sucesso!'
    else:
        msg = "Falha na conexão!"
    
    notification.notify(
    title=f'STATUS DA CONEXÃO',
    message=f'{msg} Cod: {reqsts}. Info: {reqrea}',
    app_name=" ",
    timeout=10)

In [4]:
url_feriados24 = 'https://brasilapi.com.br/api/feriados/v1/2024' # lista dos feriados nacionais em 2024.
url_pix = 'https://brasilapi.com.br/api/pix/v1/participants' # lista de instituções bancárias que utilizam o pix no país.
url_corretoras = 'https://brasilapi.com.br/api/cvm/corretoras/v1' # corretoras de valores do país.

url_error = 'https://brasilapi.com.br/api/feriados/v1/20xx' # uma url com erro para validação da 'def'

In [5]:
result_req(url_error)

In [6]:
df_feriados24 = pd.DataFrame(requests.get(url_feriados24).json())
df_pix = pd.DataFrame(requests.get(url_pix).json())
df_corretoras = pd.DataFrame(requests.get(url_corretoras).json())

In [7]:
df_feriados24

          date                      name      type
0   2024-01-01  Confraternização mundial  national
1   2024-02-13                  Carnaval  national
2   2024-03-29         Sexta-feira Santa  national
3   2024-03-31                    Páscoa  national
4   2024-04-21                Tiradentes  national
5   2024-05-01           Dia do trabalho  national
6   2024-05-30            Corpus Christi  national
7   2024-09-07   Independência do Brasil  national
8   2024-10-12   Nossa Senhora Aparecida  national
9   2024-11-02                   Finados  national
10  2024-11-15  Proclamação da República  national
11  2024-12-25                     Natal  national

In [8]:
df_feriados24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    12 non-null     object
 1   name    12 non-null     object
 2   type    12 non-null     object
dtypes: object(3)
memory usage: 420.0+ bytes

In [9]:
df_pix

,ispb,nome,nome_reduzido,modalidade_participacao,tipo_participacao,inicio_operacao
0,00000000,BANCO DO BRASIL S.A.,BCO DO BRASIL S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
1,00000208,BRB - BANCO DE BRASILIA S.A.,BRB - BCO DE BRASILIA S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
2,00068987,COOPERATIVA DE CRÉDITO ARACREDI LTDA. - SICOOB...,CC ARACREDI LTDA.,PDCT,IDRT,2020-11-03T09:30:00.000Z
3,00075847,COOPERATIVA DE CRÉDITO UNICRED CENTRO-SUL LTDA...,CC UNICRED CENTRO-SUL LTDA - UNICRED CENTRO-SUL,PDCT,IDRT,2020-11-03T09:30:00.000Z
4,00106180,CENTRAL DAS COOPERATIVAS DE CRÉDITO DOS ESTADO...,"CCC DOS EST DE MT, MS E MUN DE CACOAL/RO",PDCT,IDRT,2020-11-03T09:30:00.000Z
...,...,...,...,...,...,...
798,95213211,"COOPERATIVA DE CRéDITO, POUPANçA E INVESTIMENT...",COOP SICREDI CAMINHO DAS ÁGUAS RS,PDCT,IDRT,2020-11-03T09:30:00.000Z
799,95424891,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI VALE DO RIO PARDO,PDCT,IDRT,2020-11-03T09:30:00.000Z
800,95594941,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI REG CENTRO RS/MG,PDCT,IDRT,2020-11-03T09:30:00.000Z
801,97259253,COOPERATIVA E ECONOMIA E CRÉDITO MÚTUO DOS MÉD...,CECM MÉDICOS PLANALTO MÉDIO RS - CREDISIS/CRED...,PDCT,IDRT,2021-10-04T12:53:10.567Z
802,97489280,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI INTEGRAÇÃO BAHIA,PDCT,IDRT,2020-11-03T09:30:00.000Z

In [10]:
df_pix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 803 entries, 0 to 802
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ispb                     803 non-null    object
 1   nome                     803 non-null    object
 2   nome_reduzido            803 non-null    object
 3   modalidade_participacao  803 non-null    object
 4   tipo_participacao        803 non-null    object
 5   inicio_operacao          803 non-null    object
dtypes: object(6)
memory usage: 37.8+ KB

In [11]:
df_corretoras

,cnpj,type,nome_social,nome_comercial,status,email,telefone,cep,pais,uf,municipio,bairro,complemento,logradouro,data_patrimonio_liquido,valor_patrimonio_liquido,codigo_cvm,data_inicio_situacao,data_registro
0,76621457000185,CORRETORAS,4UM DTVM S.A.,4UM INVESTIMENTOS,CANCELADA,controle@4um.com.br,33519966,80420210,BRASIL,PR,CURITIBA,CENTRO,4º ANDAR,R. VISCONDE DO RIO BRANCO 1488,2005-12-31,4228660.18,2275,2006-10-05,1968-01-15
1,33817677000176,CORRETORAS,ABC BRASIL DISTRIBUIDORA DE TÍTULOS E VALORES ...,ABC BRASIL CORRETORA,CANCELADA,complianceregulatorio@abcbrasil.com.br,31702172,1453000,EGITO,SP,SÃO PAULO,ITAIM BIBI,2º ANDAR,"AV. CIDADE JARDIM, 803",2002-12-31,0.00,3514,2002-10-14,2002-10-14
2,10664027000132,CORRETORAS,ABERTURA CCVM LTDA,ABERTURA CCVM LTDA,CANCELADA,,,50010240,BRASIL,PE,RECIFE,,,R DO IMP.D.PEDRO II 239/CJ.102,1989-12-31,5995252.29,329,1990-06-12,1986-07-08
3,44527444000155,CORRETORAS,ABN AMRO CORRETORA DE T-TULOS E VALORES MOBILI...,,EM FUNCIONAMENTO NORMAL,canal.comunicacao@br.abnamro.com,30737417,4551010,,SP,SÃO PAULO,VILA OLIMPIA,"11¦ ANDAR, CJ. 111","RUA FIDÛNCIO RAMOS, N¦ 302, TORRE B",2022-12-31,3729687.41,3794,2022-06-20,2022-06-20
4,33819590000138,CORRETORAS,AÇÃO S.A. CORRETORA DE VALORES E CÂMBIO,ACAO SA CVC,CANCELADA,,5095755,20040040,BRASIL,RJ,RIO DE JANEIRO,CENTRO,,"PRAÇA OLAVO BILAC, 28/ SL. 608",2000-12-31,291862.38,1112,2001-04-11,1968-04-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,01170892000131,CORRETORAS,VOTORANTIM CTVM LTDA,VOTORANTIM,CANCELADA,demandasregulatorias@bancovotorantim.com.br,51711894,4794000,BRASIL,SP,SÃO PAULO,VL.GERTRUDES,TORRE A-14º ANDAR,"AV DAS NAÇÕES UNIDAS, 14.171",2017-12-31,266791832.77,3166,2018-08-27,1996-03-15
370,61769790000169,CORRETORAS,WALPIRES S/A CCTVM,WALPIRES S/A CCTVM,CANCELADA,andre@walpires.com.br,28087065,1452002,BRASIL,SP,SÃO PAULO,JARDIM PAULISTANO,1309 - 9ºANDAR,AVENIDA BRIGADEIRO FARIA LIMA,2017-12-31,7464373.90,1902,2019-09-24,1967-09-20
371,92875780000131,CORRETORAS,WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMB...,WARREN CORRETORA,EM FUNCIONAMENTO NORMAL,juridico@warren.com.br,32372273,90035191,EGITO,RS,PORTO ALEGRE,BOM FIM,2º ANDAR,"AVENIDA OSVALDO ARANHA, 720",2022-12-31,23398120.52,2534,1967-12-06,1967-12-06
372,24543688000114,CORRETORAS,WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMB...,PERFIL,CANCELADA,,2249022,52061540,BRASIL,PE,RECIFE,CASA FORTE,,"AV.17 DE AGOSTO,2579",1996-12-31,608260.02,2658,1997-02-21,1989-11-14
373,02332886000104,CORRETORAS,XP INVESTIMENTOS CCTVM S.A.,XP INVESTIMENTOS,EM FUNCIONAMENTO NORMAL,fabricio.almeida@xpi.com.br,30272237,22440032,,RJ,RIO DE JANEIRO,LEBLON,5º ANDAR,AVENIDA ATAULFO DE PAIVA 153,2022-12-31,8288904369.58,3247,1998-02-10,1997-12-05

In [12]:
df_corretoras.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   cnpj                      374 non-null    object
 1   type                      374 non-null    object
 2   nome_social               374 non-null    object
 3   nome_comercial            374 non-null    object
 4   status                    374 non-null    object
 5   email                     374 non-null    object
 6   telefone                  374 non-null    object
 7   cep                       374 non-null    object
 8   pais                      374 non-null    object
 9   uf                        374 non-null    object
 10  municipio                 374 non-null    object
 11  bairro                    374 non-null    object
 12  complemento               374 non-null    object
 13  logradouro                374 non-null    object
 14  data_patrimonio_liquido   374 non-null    object
 15  valor_patrimonio_liquido  374 non-null    object
 16  codigo_cvm                374 non-null    object
 17  data_inicio_situacao      374 non-null    object
 18  data_registro             374 non-null    object
dtypes: object(19)
memory usage: 55.6+ KB